# Inspired from: https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:fermium

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - persist_to_workspace:
          root: ~/repo
          paths: [ . ]
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: [ . ]
  publishnodelib:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public
  publishdockerimage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build Docker image
          command: docker build --tag apispecmd-ts .
      - run:
          name: Login to Docker
          command: docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID $DOCKER_HUB_PWD
#      - run:
#          name: Tag and push latest
#          command: |
#            docker tag apispecmd-ts $DOCKER_HUB_USER_ID/apispecmd-ts:latest
#            docker push $DOCKER_HUB_USER_ID/apispecmd-ts:latest
      - run:
          name: Tag and push tag version
          command: |
            echo $CIRCLE_TAG
#            docker tag apispecmd-ts $DOCKER_HUB_USER_ID/apispecmd-ts:$CIRCLE_TAG
#            docker push $DOCKER_HUB_USER_ID/apispecmd-ts:$CIRCLE_TAG
      - run:
          name: Logout from Docker
          command: docker logout

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only: main
      - publishnodelib:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publishdockerimage:
          requires:
            - publishnodelib
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
